config/routes.rb
Rails.application.routes.draw do
  devise_for :users
root "grams#index"
resources :grams do
  member do
    put 'upvote', to: 'grams#upvote'
    put 'downvote', to: 'grams#downvote'
    get :vote_up
  end
resources :comments, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gram
  belongs_to :user
end

app/models/gram.rb
class Gram < ApplicationRecord
  acts_as_voteable
  validates :title, presence: true, length: { maximum: 50, minimum: 3 }
  validates :message, presence: true
  has_many :comments

  mount_uploader :picture, PictureUploader
  belongs_to :user

  def self.search(search)
  # Title is for the above case, the OP incorrectly had 'name'
    where("title LIKE ?", "%#{search}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_voter
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :grams
  has_many :comments

  def self.upvote(id)
    self.where(:id => id).update_all("upvotes = upvotes + 1")
  end

  def self.downvote(id)
    self.where(:id => id).update_all("downvotes = downvotes + 1")
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base

  scope :for_voter, lambda { |*args| where(["voter_id = ? AND voter_type = ?", args.first.id, args.first.class.base_class.name]) }
  scope :for_voteable, lambda { |*args| where(["voteable_id = ? AND voteable_type = ?", args.first.id, args.first.class.base_class.name]) }
  scope :recent, lambda { |*args| where(["created_at > ?", (args.first || 2.weeks.ago)]) }
  scope :descending, lambda { order("created_at DESC") }

  belongs_to :voteable, :polymorphic => true
  belongs_to :voter, :polymorphic => true

  attr_accessible :vote, :voter, :voteable if ActiveRecord::VERSION::MAJOR < 4


  # Comment out the line below to allow multiple votes per user.
  validates_uniqueness_of :voteable_id, :scope => [:voteable_type, :voter_type, :voter_id]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  def render_not_found(status=:not_found)
    render plain: "#{status.to_s.titleize} :(", status: status
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def create
    @gram = Gram.find_by_id(params[:gram_id])
    return render_not_found if @gram.blank?

    @gram.comments.create(comment_params.merge(user: current_user))
    redirect_to root_path
  end

  private
  
  def comment_params
    params.require(:comment).permit(:message)
  end
end

app/controllers/grams_controller.rb
class GramsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :upvote, :downvote]

  def index
    if params[:search]
      @grams = Gram.search(params[:search]).page(params[:page]).per_page(25).order('created_at DESC')
    else
      @grams = Gram.all.page(params[:page]).per_page(25).order('created_at DESC')
    end
  end

  def new
    @gram = Gram.new
  end

  def create
    @gram = current_user.grams.create(gram_params)

    if @gram.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @gram = Gram.find_by_id(params[:id])
    return render_not_found if @gram.blank?
  end

  def edit
    @gram = Gram.find_by_id(params[:id])
    return render_not_found if @gram.blank?
    return render_not_found(:forbidden) if @gram.user != current_user
  end

  def update
    @gram = Gram.find_by_id(params[:id])
    return render_not_found if @gram.blank?
    return render_not_found(:forbidden) if @gram.user != current_user

    @gram.update_attributes(gram_params)
    if @gram.valid?
      redirect_to root_path
    else
      return render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @gram = Gram.find_by_id(params[:id])
    return render_not_found if @gram.blank?
    return render_not_found(:forbidden) if @gram.user != current_user
    @gram.destroy
    redirect_to root_path
  end

def upvote
  @gram = Gram.find(params[:id])
  current_user.vote_exclusively_for(@gram)

  redirect_to gram_path(@gram)
end

def downvote
  @gram = Gram.find(params[:id])
  current_user.vote_exclusively_against(@gram)

  redirect_to gram_path(@gram)
end

  private

  def gram_params
    params.require(:gram).permit(:message)
  end

  def gram_params
      params.require(:gram).permit(:message, :picture, :title)
    end

    def vote_up
    begin
      current_user.vote_for(@gram = Gram.find(params[:id]))
      render :nothing => true, :status => 200
    rescue ActiveRecord::RecordInvalid
      render :nothing => true, :status => 404
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/grams_helper.rb
module GramsHelper
end

app/views/grams/edit.html.erb
<div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3 card form">
  <h2>Edit Post</h2>

<%= simple_form_for @gram do |f| %>
  <%= f.input :title %>
  <%= f.input :message %>
  <%= f.input :picture %>
  <%= f.submit 'Update', class: 'my-btn' %>
<% end %>

</div>

app/views/grams/index.html.erb
<div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3">
  <br />
  <table class="table table-sm">
    <tbody>
      <% @grams.each do |gram| %>

        <tr>
          <td><%= link_to image_tag(gram.picture, class: 'img-fluid thumb'), gram_path(gram) %></td>
          <td class="align-middle"><%= link_to gram.title, gram_path(gram), class:'img-fluid thumb' %></td>
          <td class="align-middle"><%= gram.user.email %></td>
        </tr>

      <% end %>
    </tbody>
  </table>
  <div class="digg_pagination">
    <div class="page_info">
      <%= page_entries_info @grams %>
    </div>
    <%= will_paginate @grams, :container => false %>
  </div>

</div>

app/views/grams/new.html.erb
<div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3 card form">
<h1>New Post</h1>

<%= simple_form_for @gram do |f| %>
  <%= f.input :title %>
  <%= f.input :message %>
  <%= f.input :picture %>
  <%= f.submit "Post!", class: 'my-btn' %>
<% end %>
</div>

app/views/grams/show.html.erb
<div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3">
    <div class="card">
      <div class="handle"><%= @gram.user.email %></div>
      <div class="text-center">
        <div class="title">
          <%= @gram.title %>
          </div>
        </div>
      <%= image_tag @gram.picture, class: 'img-fluid' %>
      <p>
        <%= @gram.message %>
      </p>

        <div class="text-center">
          <h2> <%= @gram.votes_for %> <%= link_to "", upvote_gram_path(@gram), method: "put", class: "fas fa-thumbs-up" %>
            <%= link_to "", downvote_gram_path(@gram), method: "put", class: "fas fa-thumbs-down" %> <%= @gram.votes_against %> </h2>
        </div>
      <br />
    <div class="text-center">
      <% if current_user && current_user == @gram.user %>
          <%= link_to 'Edit', edit_gram_path(@gram), class: 'btn btn-primary' %>
          <%= link_to 'Destroy', gram_path(@gram), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-primary' %>
      <% end %>
    </div>
    <br class="clear-fix" />
    <div class="comments">
      <h3>Comments</h3>
      <% @gram.comments.each do |comment| %>
          <div class="comment">
            <span class="comment_handle">
              <%= comment.user.email %>-
            </span>
            <br />
            <%= comment.message %>
          </div>
            ------------------------------
      <% end %>
      <br />
      <h4>Add a comment</h4>
      <%= simple_form_for Comment.new, url: gram_comments_path(@gram) do |f| %>
        <%= f.input :message %>
        <%= f.submit 'Add Comment', class: 'my-btn' %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">Meddit</a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
    </ul>
    <form class="form-inline my-2 my-lg-0">

      <% if current_user %>
             Welcome, <%= current_user.email %> &nbsp;
            <%= link_to "New Post", new_gram_path, class: 'spacer' %>
            <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: 'spacer' %>
          <% else %>
            <%= link_to "Sign In", new_user_session_path, class: 'spacer' %>
            <%= link_to "Sign Up", new_user_registration_path, class: 'spacer' %>
          <% end %>
        <%= form_tag(grams_path, :method => "get", id: "search-form") do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search Posts" %>
          <%= submit_tag "Search" %>
        <% end %>
    </form>
  </div>
</nav>




      <% if alert.present? %>
        <p class="alert"><%= alert %></p>
      <% end %>
      <% if notice.present? %>
        <p class="alert alert-info"><%= notice %></p>
      <% end %>

    <%= yield %>
  </body>
</html>